# File Processor Worker Component
#
# KEDA-scaled worker for async file processing from SQS

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Uses rem-app service account (created in api component) with Pod Identity
  - deployment.yaml
  # KEDA resources
  - keda-scaledobject.yaml
  - triggerauthentication.yaml
