# Service Account for file-processor worker
#
# Uses IRSA (IAM Roles for Service Accounts) to grant AWS permissions
# - SQS: ReceiveMessage, DeleteMessage, GetQueueAttributes
# - S3: GetObject, PutObject

apiVersion: v1
kind: ServiceAccount
metadata:
  name: file-processor
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::852140462228:role/application-cluster-a-app  # CDK-created IAM role
