apiVersion: v1
kind: Service
metadata:
  name: phoenix
  namespace: phoenix-system
  labels:
    app.kubernetes.io/name: phoenix
    app.kubernetes.io/component: observability
spec:
  type: ClusterIP
  ports:
    - port: 6006
      targetPort: http
      protocol: TCP
      name: http
    - port: 4317
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    app.kubernetes.io/name: phoenix
    app.kubernetes.io/component: observability
